apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docmost/docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: docmost
  name: docmost
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: docmost
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docmost/docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: docmost
    spec:
      containers:
        - env:
            - name: APP_SECRET
              value: REPLACE_WITH_LONG_SECRET
            - name: APP_URL
              value: http://localhost:3000
            - name: DATABASE_URL
              value: postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost
            - name: REDIS_URL
              value: redis://redis:6379
          image: docmost/docmost:latest
          name: docmost
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data/storage
              name: docmost
      restartPolicy: Always
      volumes:
        - name: docmost
          persistentVolumeClaim:
            claimName: docmost
